// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDesgLarCE3wg5Hvp9uvXSvDPDaA-OQLC4',
    appId: '1:212579021842:web:e74125741523e4552554cb',
    messagingSenderId: '212579021842',
    projectId: 'nabtati-cb3a1',
    authDomain: 'nabtati-cb3a1.firebaseapp.com',
    storageBucket: 'nabtati-cb3a1.firebasestorage.app',
    measurementId: 'G-EXTWKHEMQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOc6uZGuPD1JObnlZcyfVJdmJCJ04DnSE',
    appId: '1:212579021842:android:68aa2d56ea56a8d22554cb',
    messagingSenderId: '212579021842',
    projectId: 'nabtati-cb3a1',
    storageBucket: 'nabtati-cb3a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3FBNi9OIQlG4tia0sbzYgqTTOnWFbVHA',
    appId: '1:212579021842:ios:8938171c8aef9db82554cb',
    messagingSenderId: '212579021842',
    projectId: 'nabtati-cb3a1',
    storageBucket: 'nabtati-cb3a1.firebasestorage.app',
    iosBundleId: 'com.example.nabtati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3FBNi9OIQlG4tia0sbzYgqTTOnWFbVHA',
    appId: '1:212579021842:ios:8938171c8aef9db82554cb',
    messagingSenderId: '212579021842',
    projectId: 'nabtati-cb3a1',
    storageBucket: 'nabtati-cb3a1.firebasestorage.app',
    iosBundleId: 'com.example.nabtati',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDesgLarCE3wg5Hvp9uvXSvDPDaA-OQLC4',
    appId: '1:212579021842:web:d3ba7e8fa8c823fd2554cb',
    messagingSenderId: '212579021842',
    projectId: 'nabtati-cb3a1',
    authDomain: 'nabtati-cb3a1.firebaseapp.com',
    storageBucket: 'nabtati-cb3a1.firebasestorage.app',
    measurementId: 'G-MPKMGGK3W0',
  );
}
